/**
 * Auto-generated TypeScript types for SVG sprite icons
 * Generated from svg-icons directory
 * 
 * DO NOT EDIT THIS FILE MANUALLY - it is auto-generated
 */

export type IconName = 'home' | 'search' | 'settings' | 'star' | 'user';

export const iconNames = ['home', 'search', 'settings', 'star', 'user'] as const;
