/**
 * Auto-generated TypeScript types for SVG sprite icons
 * Generated from svg-icons directory
 * 
 * DO NOT EDIT THIS FILE MANUALLY - it is auto-generated
 */

export type IconName = 'brands:apple' | 'brands:google' | 'home' | 'search' | 'settings' | 'star' | 'sun-moon' | 'user' | 'social:facebook' | 'social:twitter';

export const iconNames = ['brands:apple', 'brands:google', 'home', 'search', 'settings', 'star', 'sun-moon', 'user', 'social:facebook', 'social:twitter'] as const;
